### PR TITLE
Trying to use custom vid resolution

### PR DESCRIPTION
**Pull request by devsdocs**
Need to test

### CODE REVIEW

**Comment by ParveenBhadooOfficial** [comment]
will be merged in next release

**Comment by ronin08** [comment]
yeah ... please test it . not sure it will work or not ...

as you can give the "quality" argument in place of "ratio" and put example as parameters i.e 360p , ... 2160p etc .

refer : https://github.com/sampotts/plyr#options

@ParveenBhadooOfficial  please look into this ...

**Comment by ParveenBhadooOfficial** [comment]
> yeah ... please test it . not sure it will work or not ...
> 
> as you can give the "quality" argument in place of "ratio" and put example as parameters i.e 360p , ... 2160p etc .
> 
> refer : https://github.com/sampotts/plyr#options
> 
> @ParveenBhadooOfficial please look into this ...

It doesn't works like that. You cannot replace `a` with `b` and expect it to work.

**Comment by ronin08** [comment]
ohk but please add the support to select video quality . it is mentioned on the official plyr.io github repo .

**Pull request merged**
