### PR TITLE
handle worker exception when file is undefined and show a 404 response

### PR DESCRIPTION
**Pull request by sainAk**

### CODE REVIEW

**Comment by ParveenBhadooOfficial** [comment]
this happens when?

**Comment by ParveenBhadooOfficial** [comment]
> it happens when you try to open a file that doesn't exist on google drive eg. https://vipercloud.ga/1:/not_found
> 
> wait don't merge it now I've found a better way to handle it
> I'll update the pr

sure.

**Comment by sainAk** [comment]
> > it happens when you try to open a file that doesn't exist on google drive eg. https://vipercloud.ga/1:/not_found
> > wait don't merge it now I've found a better way to handle it
> > I'll update the pr
> 
> sure.

okay now it's ready to merge

I have some qiestions can we chat on telegram, is @TheFirstSpeedster your id?

**Comment by ParveenBhadooOfficial** [comment]
> > > it happens when you try to open a file that doesn't exist on google drive eg. https://vipercloud.ga/1:/not_found
> > > wait don't merge it now I've found a better way to handle it
> > > I'll update the pr
> > 
> > 
> > sure.
> 
> okay now it's ready to merge
> 
> I have some questions can we chat on telegram, is @TheFirstSpeedster your id?

yes. DM.

**Pull request merged**
